apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datawave.fullname" . }}-ingest
  labels:
    {{- include "datawave.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  replicas: {{ .Values.ingest.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ingest
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ingest
    spec:
      hostname: ingestmaster
      initContainers:
      - name: accumulo-classpath-loader
        image: {{ .Values.ingest.image.repository }}:{{ .Values.ingest.image.tag }}
        command: ["/bin/bash", "/cmds/run.sh"]
        volumeMounts:
        - name: init-container-cmds
          mountPath: /cmds
          readOnly: true
        - name: yumrepo
          mountPath: /secrets
          readOnly: true
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
      - name: init-accumulo
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup accumulo-master; do echo waiting for accumulo; sleep 2; done"]
 
      containers:
      - name: ingest
        image: {{ .Values.ingest.image.repository }}:{{ .Values.ingest.image.tag }}
        imagePullPolicy: {{ .Values.ingest.image.pullPolicy }}
        resources:
          {{- toYaml .Values.ingest.deployment.resources | nindent 10 }}
        command: ["/bin/bash", "/cmds/run.sh"]
        volumeMounts:
        - name: cmds
          mountPath: /cmds
          readOnly: true
        - name: yumrepo
          mountPath: /secrets
          readOnly: true
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
      volumes:
      - name: hadoop-config
        configMap:
          name: dwv-dwv-hadoop
      - name: cmds
        secret:
          secretName: {{ include "datawave.fullname" . }}-cmds
          optional: false
      - name: init-container-cmds
        secret:
          secretName: {{ include "datawave.fullname" . }}-initconatiner-cmds
          optional: false
      - name: yumrepo
        secret:
          secretName: {{ include "datawave.fullname" . }}-repo
          optional: false
      {{- with .Values.ingest.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
