
{{- define "datawave.datawaveInstallScript" -}}
#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
echo "Symlinking Artifactory Repo"
ln -s /secrets/artifactory.repo /etc/yum.repos.d/artifactory.repo

echo "Creating logs directory and opening permissions"
mkdir -p /srv/logs/ingest
chmod 777 -R /srv/logs/

echo "Create Accumulo Namespace"
/opt/accumulo/bin/accumulo shell -u root -p root -e "createnamespace datawave"

echo "Copying hadoop config to accumulo dir"
cp -L -R /tmp/hadoop-config/* /opt/accumulo/conf/
mkdir -p /usr/local/hadoop/etc/hadoop/
cp -L -R /tmp/hadoop-config/* /usr/local/hadoop/etc/hadoop/

echo "Install Datawave Dev"
yum -y install datawave-dw-dev-{{  .Values.ingest.datawaveVersion }}-1


echo "Symlinking Password file"
ln -s /cmds/ingest-passwd.sh /opt/datawave-ingest/ingest-passwd.sh

echo "Creating Flag File directory and making it owned by datawave"
mkdir -p /srv/data/datawave/flags
chown datawave -R /srv/data


echo "Symlinking genders file"
ln -s /cmds/genders /etc/genders

echo "Create datawave tables"
/opt/datawave-ingest/current/bin/ingest/create-all-tables.sh 

echo "Starting datawave ingest"
runuser -l datawave -c '/opt/datawave-ingest/current/bin/system/start-all.sh'

tail -f /dev/null


{{- end -}}
{{- define "datawave.genders" -}}
hdfs-nn namenode
zookeeper zookeeper
ingestmaster ingestmaster
#TODO add in all the services, including ingest here.

{{- end -}}

{{- define "datawave.passwdfile" -}}
#TODO update to pass passwors in as secrets.
export PASSWORD=root
export KEYSTORE_PASSWORD=root
export TRUSTSTORE_PASSWORD=root

{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawave.fullname" . }}-cmds
  labels:
    {{- include "datawave.labels" . | nindent 4 }}
type: Opaque
data:
  run.sh: {{ include "datawave.datawaveInstallScript" . | b64enc }}
  ingest-passwd.sh: {{ include "datawave.passwdfile" . | b64enc }}
  genders: {{ include "datawave.genders" . | b64enc }}
