version: '2.1'
services:
  messaging:
    environment:
      - TCP_PORTS=15672, 5672
      - AUTOCLUSTER_TYPE=consul
      - AUTOCLUSTER_DELAY=60
      - CONSUL_HOST=discovery
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_DEREGISTER_AFTER=60
    networks:
      - back
    image: pivotalrabbitmq/rabbitmq-autocluster:3.6.12
    ports:
      - "15672:15672"
    expose:
      - 5672
      - 5671
      - 15671
    tty: true
    command: sh -c "sleep 10; rabbitmq-server;"

  discovery:
    image: consul
    hostname: discovery
    container_name: discovery
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back

  configuration:
    image: datawave/config-service
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=dev,consul
      - --spring.cloud.consul.host=discovery
      - --spring.cloud.bus.enabled=true
      - --management.health.rabbit.enabled=true
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/config:/tmp/microservice-config
      - ${PWD}/config_git_metadata:/tmp/microservice-config/.git
    networks:
      - back

  audit:
    image: datawave/audit-service
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul
      - --spring.cloud.consul.host=discovery
    ports:
      - "8080:8080"
    networks:
      - back

networks:
  back:
