# DataWave project repo
repository_url: https://github.com/NationalSecurityAgency/datawave

# gh-pages site repo. This config property is required when running the site in production mode
repository: NationalSecurityAgency/datawave

# Base URL to allow relative paths to work correctly on GitHub. Note: as a side effect of this
# you'll need to run the site locally with "jekyll serve --baseurl '' ... " in order for things to work
baseurl: /datawave

# max news posts to display on the home page
num_home_posts: 8

# org name for the footer
organization_name: National Security Agency

# org url for the footer
organization_url: https://github.com/NationalSecurityAgency

# base path to the branch we'll be using for PR's; leaving as gh-pages for now.
github_editme_path: NationalSecurityAgency/datawave/edit/gh-pages/

# TODO: get google-analytics ID.
google_analytics:

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - scripts/
  - .gitignore
  - README.md

feedback_subject_line:
feedback_email:
feedback_disable: true
feedback_text: "Contact Us"
feedback_link: "http://github.com/NationalSecurityAgency/datawave"

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# this description is used in /feed.xml
description: "DataWave is a Java-based ingest and query framework that leverages Apache Accumulo to provide fast, secure access to your data"

# Enable site plugins as needed...

# We're using the 'jekyll-redirect-from' plugin to enable simplified internal and external href links,
# i.e., href targets that are agnostic to specific DW doc versions. See _docs-latest/*.md files for examples   

whitelist: [jekyll-redirect-from]
plugins: [jekyll-redirect-from]

##########################################################
# Site update instructions for new DW versions:
#
# For doc changes pertaining to minor or patch releases of DW, you can probably skip
# straight to step (9) below, i.e., for content-only (non-structural) changes.
#
# For doc updates related to a new major release, you'll need to start with step (1) below.
#
# (1) Copy the existing _docs-latest to a new backup folder (aka "collection"), since it's now the "old" version. E.g.,...
#
#     cp -a _docs-latest  _docs-7x (Note: maintaining the underscore prefix is important)
#
# (2) Delete the 'redirect' files from the "old" version, since we prefer to only maintain one set. E.g.,...
#
#     rm -f _docs-7x/index.md _docs-7x/data-model.md _docs-7x/quickstart.md _docs-7x/tour.md
#
# (3) Update the 'redirect' files in _docs-latest to reflect the new major version as needed. E.g.,...
#
#     sed -i 's/7.x/8.x/g' _docs-latest/*.md
#
# (4) Backup the current _data/sidebars/docs-latest-sidebar.yml to maintain compatibility with the "old" docs version. E.g.,...
#
#     cp _data/sidebars/docs-latest-sidebar.yml  _data/sidebars/docs-7x-sidebar.yml
#
# (5) Update _data/sidebars/docs-latest-sidebar.yml to reflect the new major version as needed. E.g.,...
#
#     sed -i 's/7.x/8.x/g' _data/sidebars/docs-latest-sidebar.yml
#
# (6) Update _data/topnav.yml to reflect the new version. No need to back this one up since we're only maintaining a
#     single top navigation bar for all docs versions, and it should always target the latest docs. E.g.,...
#
#     sed -i 's/7.x/8.x/g' _data/topnav.yml
#
# (7) _config.yml: Update the "collections" yaml section below as necessary to preserve permalinks for the new and old versions.
#
#     E.g., copy the "docs-latest" stanza below to a new "docs-6x" stanza, and update the "docs-latest" permalink to reflect
#     the new 8.x major version 
#
# (8) _config.yml: Update Frontmatter "defaults" yaml below as necessary, similar to step #7 above, making sure to
#     configure the 'scope:type', 'values:sidebar', and 'values:release_tag' properties for the new and old docs versions  
#
# (9) Make any version-specific content updates to the _docs-latest/*/*.md files for the new DW release
#
# (10) Locally test all site changes. See README.md for instructions on running the site

##########################################################
# Docs collection definitions...

collections: 
  # The "docs-latest" collection renders _docs-latest folder contents to the configured permalink path.
  # Note the relationship between this collection and the frontmatter config below where scope.type == 'docs-latest' 
  docs-latest:
    output: true
    permalink: "/docs/7.x/:path"
  
  # The "docs-6x" collection renders _docs-6x folder contents to the configured permalink path.
  # Note the relationship between this collection and the frontmatter config below where scope.type == 'docs-6x' 
  docs-6x:
    # Set 'output: false' to disable rendering of 6.x docs
    output: true
    permalink: "/docs/6.x/:path"

  # Likewise, "docs-5x" below renders _docs-5x folder contents, so that users can still navigate to the old docs
  # Note the relationship between this collection and the frontmatter config below where scope.type == 'docs-5x'  
  docs-5x:
    # Set 'output: false' to disable rendering of 5.x docs
    output: true
    permalink: "/docs/5.x/:path"
    
  # There was never a 4.x DW release, for a variety of reasons...

  # Likewise, "docs-3x" below renders _docs-3x folder contents, so that users can still navigate to the old docs
  # Note the relationship between this collection and the frontmatter config below where scope.type == 'docs-3x'
  docs-3x:
    # Set 'output: false' to disable rendering of 3.x docs
    output: true
    permalink: "/docs/3.x/:path"
    
##########################################################
# Frontmatter defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      skip_title_for_h1: false
      toc: false
      topnav: topnav
  -
    scope:
      path: "pages/tags"
      type: "pages"
    values:
      layout: "page"
      title_prefix: "Site Tag: "
      toc: false
      skip_title_for_h1: true
      topnav: topnav
  -
    scope:
      path: "_posts/news"
      type: "posts"
    values:
      layout: "news"
      category: "news"
      permalink: "/:categories/:year/:month/:day/:title"
      title_prefix: "DataWave News - "
      skip_title_for_h1: false
      toc: false
      topnav: topnav
  -
    scope:
      path: "_posts/release"
      type: "posts"
    values:
      layout: "release"
      category: "release"
      permalink: "/:categories/:title/"
      skip_title_for_h1: false
      toc: false
      topnav: topnav
  -
    # set frontmatter defaults for the previous DW 3.x docs "collection"
    scope:
      path: ""
      type: "docs-3x"
    values:
      layout: "docs"
      title_prefix: "DataWave 3.x Docs - "
      sidebar: docs-3x-sidebar
      # Note that release_tag is a page-scoped variable that is used for, among
      # other things, a means of creating href links to specific source files
      # on the main datawave repo, sometimes to specific line #'s in a given source
      # file. Thus, changing the release_tag here can potentially break things
      release_tag: 3.41.8
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -  
    # set frontmatter defaults for the previous DW 5.x docs "collection"
    scope:
      path: ""
      type: "docs-5x"
    values:
      layout: "docs"
      title_prefix: "DataWave 5.x Docs - "
      sidebar: docs-5x-sidebar
      # Note that release_tag is a page-scoped variable that is used for, among
      # other things, a means of creating href links to specific source files
      # on the main datawave repo, sometimes to specific line #'s in a given source
      # file. Thus, changing the release_tag here can potentially break things
      release_tag: 5.10.0
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # set frontmatter defaults for the previous DW 6.x docs "collection"
    scope:
      path: ""
      type: "docs-6x"
    values:
      layout: "docs"
      title_prefix: "DataWave 6.x Docs - "
      sidebar: docs-6x-sidebar
      # Note that release_tag is a page-scoped variable that is used for, among
      # other things, a means of creating href links to specific source files
      # on the main datawave repo, sometimes to specific line #'s in a given source
      # file. Thus, changing the release_tag here can potentially break things
      release_tag: 6.5.5
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # set frontmatter defaults for the current DW docs version
    scope:
      path: ""
      type: "docs-latest"
    values:
      layout: "docs"
      title_prefix: "DataWave 7.x Docs - "
      sidebar: docs-latest-sidebar
      # Note that release_tag is a page-scoped variable that is used for, among
      # other things, a means of creating href links to specific source files
      # on the main datawave repo, sometimes to specific line #'s in a given source
      # file. Thus, changing the release_tag here can potentially break things
      release_tag: 7.2.1
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav

# Note about sidebar-menu navigation:
# Sidebar navigation for each page in a docs collection is data- and configuration-driven. See _data/sidebars for
# example sidebar yaml definitions, and see _includes/sidebar.html, which handles sidebar rendering for any page type
# that configures the 'sidebar' property in its frontmatter
