#############################################################################
# Global site config properties
#############################################################################

# DataWave project repo
repository_url: https://github.com/NationalSecurityAgency/datawave

# gh-pages site repo. This config property is required when running
# the site in production mode
repository: NationalSecurityAgency/datawave

# Base URL to allow relative paths to work correctly on GitHub.
# Note: as a side effect of this, in order for things to work
# correctly when you're running the site locally, you'll need
# to run the site with "jekyll serve --baseurl '' ... "
baseurl: /datawave

# max news posts to display on the home page
num_home_posts: 8

# org name for the footer
organization_name: National Security Agency

# org url for the footer
organization_url: https://github.com/NationalSecurityAgency

# base path to the branch we'll be using for PR's; leaving as gh-pages for now.
github_editme_path: NationalSecurityAgency/datawave/edit/gh-pages/

# TODO: get google-analytics ID.
google_analytics:

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - scripts/
  - .gitignore
  - README.md

feedback_subject_line:
feedback_email:
feedback_disable: true
feedback_text: "Contact Us"
feedback_link: "http://github.com/NationalSecurityAgency/datawave"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Description is used in /feed.xml
description: "DataWave is a Java-based ingest and query framework that leverages Apache Accumulo to provide fast, secure access to your data"

# Enable site plugins as needed...

# We're using the 'jekyll-redirect-from' plugin to allow for simplified
# internal and external href links, i.e., href targets that are agnostic
# to specific DW doc versions. See _docs-latest/*.md files for examples   

whitelist: [jekyll-redirect-from]
plugins: [jekyll-redirect-from]

#############################################################################
# Site update instructions for new DW versions
#############################################################################

# For doc changes pertaining to minor or patch releases of DW, you can
# probably skip straight to step 9 below, i.e., for content-only,
# non-structural changes.

# For doc updates related to a new major release, structural changes
# are required, so you'll need to start with step 1 below.

# NOTE: Use 'scripts/prep-next-major-release-docs' to automate 1-6 below

# (1) Assuming 8.x is the next major release, copy the existing
#     _docs-latest (7.x) to a new "collection" directory
#
#     cp -a _docs-latest  _docs-7x
#
#     Note: maintaining the underscore prefix is important

# (2) Delete the 'redirect' files from the "old" version. We 
#     want to maintain only the ones in _docs-latest/
#
#     rm -f _docs-7x/*.md

# (3) Update the redirect files in _docs-latest to reflect the new
#     major version
#
#     sed -i 's/7.x/8.x/g' _docs-latest/*.md

# (4) Copy the current _data/sidebars/docs-latest-sidebar.yml
#     to preserve compatibility with the old docs version
#
#     cd _data/sidebars
#     cp docs-latest-sidebar.yml docs-7x-sidebar.yml

# (5) Update _data/sidebars/docs-latest-sidebar.yml to reflect
#     the new major version
#
#     sed -i 's/7.x/8.x/g' _data/sidebars/docs-latest-sidebar.yml

# (6) Update _data/topnav.yml to reflect the new version. No need to
#     back this one up since we're only maintaining a single top
#     navigation bar for all pages in the site, and topnav.yml will
#     always reference the latest docs version
#
#     sed -i 's/7.x/8.x/g' _data/topnav.yml

# (7) Update _config.yml "collections":
#
#     Following existing examples below, update the collections as
#     necessary to preserve permalinks for the new and old versions.
#
#     That is, copy the "docs-latest" stanza below to a new "docs-7x"
#     stanza, and update the "docs-latest" permalink to reflect the
#     new 8.x version 

# (8) Update _config.yml "frontmatter" defaults:
#
#     Following existing examples below, update the frontmatter defaults
#     below as necessary, similar to step 7 above. Make sure to configure
#     the 'scope.type', 'values.sidebar', and 'values.release_tag'
#     properties appropriately for the new and old versions  

# (9) Make version-specific content updates to anything under
#     _docs-latest/ as needed for the current DW release

# (10) Locally test all site changes. See README.md for instructions on
#      running the site

#############################################################################
# Docs Collection Configuration
#############################################################################

# Note: The best way to prevent a deprecated/unwanted collection
# from being rendered is to set 'output: false' below. E.g., if
# the time it takes to build and render the site ever becomes
# excessive, there's no need to delete ancient _docs-* dirs.
# Just turn off rendering of the collection

collections:
  # The "docs-latest" collection renders _docs-latest folder
  # contents to the configured permalink path. Note that there's
  # an implicit relationship between this collection and the
  # frontmatter config below where scope.type == 'docs-latest' 
  docs-latest:
    output: true
    permalink: "/docs/7.x/:path"
  
  # Renders _docs-6x folder contents. See frontmatter configs
  # below where scope.type == 'docs-6x'
  docs-6x:
    output: true
    permalink: "/docs/6.x/:path"

  # Renders _docs-5x folder contents. See frontmatter configs
  # below where scope.type == 'docs-5x'  
  docs-5x:
    output: true
    permalink: "/docs/5.x/:path"
  
  # There was never a 4.x DW release, for a variety of reasons

  # Renders _docs-3x folder contents. See frontmatter configs
  # below where scope.type == 'docs-3x'
  docs-3x:
    output: true
    permalink: "/docs/3.x/:path"

#############################################################################
# Frontmatter Defaults. Override on a per-page (*.md) basis, if needed
#############################################################################

# Note that the values.topnav property is always 'topnav'
# below, which configures _data/topnav.yml as the primary
# navigation bar for *all* pages in the site

# Note regarding sidebar menu navigation:
# Sidebar navigation for each page in a docs collection
# is configuration-driven (see _data/sidebars/*.yml for
# example configs). And rendering of the sidebar is handled
# by _includes/sidebar.html based on the 'sidebar'
# property specified below for the given collection
# (i.e., scope.type)

defaults:
  -
    # Frontmatter defaults for the current DW version (_docs-latest dir)
    scope:
      path: ""
      type: "docs-latest"
    values:
      layout: "docs"
      title_prefix: "DataWave 7.x Docs - "
      sidebar: docs-latest-sidebar
      # Note that 'release_tag' is a page-scoped variable that is used for, among
      # other things, a means of creating href links to specific source files
      # on the main datawave repo, sometimes for specific line #'s in a given source
      # file. Thus, changing the release_tag here can potentially break things
      release_tag: 7.2.1
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # Frontmatter defaults for DW 6.x (_docs-6x dir)
    scope:
      path: ""
      type: "docs-6x"
    values:
      layout: "docs"
      title_prefix: "DataWave 6.x Docs - "
      sidebar: docs-6x-sidebar
      release_tag: 6.5.5
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # Frontmatter defaults for DW 5.x (_docs-5x dir)
    scope:
      path: ""
      type: "docs-5x"
    values:
      layout: "docs"
      title_prefix: "DataWave 5.x Docs - "
      sidebar: docs-5x-sidebar
      release_tag: 5.10.0
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # Frontmatter defaults for DW 3.x (_docs-3x dir)
    scope:
      path: ""
      type: "docs-3x"
    values:
      layout: "docs"
      title_prefix: "DataWave 3.x Docs - "
      sidebar: docs-3x-sidebar
      release_tag: 3.41.8
      show_summary: true
      skip_title_for_h1: false
      toc: true
      topnav: topnav
  -
    # Frontmatter defaults for any pages/*.md
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      skip_title_for_h1: false
      toc: false
      topnav: topnav
  -
    # Frontmatter defaults for any pages/tags/*.md
    scope:
      path: "pages/tags"
      type: "pages"
    values:
      layout: "page"
      title_prefix: "Site Tag: "
      toc: false
      skip_title_for_h1: true
      topnav: topnav
  -
    # Frontmatter defaults for any _posts/news/*.md
    scope:
      path: "_posts/news"
      type: "posts"
    values:
      layout: "news"
      category: "news"
      permalink: "/:categories/:year/:month/:day/:title"
      title_prefix: "DataWave News - "
      skip_title_for_h1: false
      toc: false
      topnav: topnav
  -
    # Frontmatter defaults for any _posts/release/*.md
    scope:
      path: "_posts/release"
      type: "posts"
    values:
      layout: "release"
      category: "release"
      permalink: "/:categories/:title/"
      skip_title_for_h1: false
      toc: false
      topnav: topnav
