####################################
# Core Helm Template Configuration #
####################################

apiVersion: networking.k8s.io/v1
kind: Ingress

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.ingress.meta.name }}"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /DataWave/$2
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-path: /services/DataWave

####################################
# Ingress Controller Specification #
####################################

spec:

  ################################################
  # Transport-Layer Security (TLS) Configuration #
  ################################################

  # tls:
  #   - hosts:
  #       - "{{ .Values.web.ingress.domains.datawave }}"

  #########################################
  # Ingress Controller Rule Configuration #
  #########################################

  rules:

    - http:
        paths:
          - path: /DataWave(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}-{{ .Values.web.datawaveService.meta.name }}"
                port: 
                  number: {{ .Values.web.datawaveService.ports.https }}
