server:
  context-path: /datawave

security:
  sessions: STATELESS
  enable-csrf: true
  user.password: passwordNotUsed
  jwt.ttl: 86400
  enforce-allowed-callers: false
  issuers-required: true

spring:
  # Enable service discovery using Consul
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: consul
      discovery:
        healthCheckPath: ${server.context-path}${management.context-path}/health
        healthCheckInterval: 15s
      # Allow a long time for the Consul agent to become available.
      retry:
        max-attempts: 120
  # Use discovery to find the RabbitMQ server
  rabbitmq:
    discovery:
      enabled: true
      failFast: true
